### PR TITLE
Separate column for Table of Contents

### PR DESCRIPTION
**Pull request by Bosterm**
This resolves issue #9. Separates table of contents from other blocks and puts it in a 3 width bootstrap column, with the main content in a 9 width bootstrap column. If there is no table of contents block, then the content on a page is full width.

### CODE REVIEW

**Comment by alexdryden** [comment]
Table of contents section currently only lists pages under the current page in the navigation hierarchy, with number of children to show configurable. However, it does not display siblings pages of the current page(i.e. the pages that you will see using the next, previous buttons). Isn't siblings what we need to show in the left hand column?

Would it work to move the navigation from the top to this side bar instead? That way sibling pages to the current page could be displayed?

---Edit---
Or would it be easier to change the way that the toc is populated? I realize it will be easier if we are both looking at the same example site, so I made a cPanel site and installed Omeka: https://pressbookstest.web.illinois.edu/omeka-s/s/test-site/page/test. I added you to the cPanel and the Omeka site. The theme is currently on this branch.

**Comment by Bosterm** [comment]
I ended up creating this as a separate issue (#19), but it may be best to fix it before we merge branches. I didn't realize the problem until I was mostly finished doing this. I think there's a few options here, depending on whether we want the table of contents to be optional or not for all pages.

1. Keep using the table of contents block as the sidebar, but rework it to show siblings.
2. Make the table of contents block function as the block for two column tile, and then create a new layout block for the sidebar navigation.

Or some other combination of using or not using blocks for these features. I'm not sure how difficult it is to create a new block and whether that involves creating a module. Part of the reason I want to do this with the blocks is to make these features optional, since having a sidebar navigation and even the two column tiles implies a certain organization for an exhibit, and some users may want to structure an exhibit to be non-linear, in which case they wouldn't want the sidebar. But then again, that's anticipating a need that may not exist.

So with all that said, perhaps for now I'll focus on getting it to work without creating new blocks and not worry about whether users are always going to want them or not. I'll see if it's easy to get the table of contents to show siblings.

**Comment by alexdryden** [comment]
Yeah, that makes sense. I think keeping it optional is strongly preferred. I was thinking that there is already the checkbox to include a page in the navigation, but people might still want a navigation separate from the toc. 

For number 1, my first thought is that to get siblings you would just need to find the next and previous page title and url recursively. That would create some issues when the exhibit structure isn't flat because when you navigate to a child page it would suddenly show only the siblings of that child page. 
Right now it looks that the toc is designed with the idea that it would only be placed on a root of the site hierarchy and you decide how many child levels to display (from the current page), but we could repurpose that option. Instead that input could determine the distance from the root to display, (e.g. show all pages within 1 generation from the root would be the default). That way the toc would look the same on every page of the exhibit, even if there were child pages. So, before building the toc it would first move to the root page (or a top level page) and evaluate how many children to show from there, instead of evaluating from the current page. 

I think adding a new block type would require a module, which might be worth doing if we want to provide users with a lot of options. But that might be better for another iteration because it involve some planning that I'm not sure we can do right now.

**Comment by Bosterm** [comment]
Yes I agree, building a new block is more complicated than we need to make it right now. It may not even be necessary to use a block for this purpose (instead just generate the navigation outside of the block feature), but for now I'm just trying to figure out exactly how Omeka S creates the navigation.

**Comment by Bosterm** [comment]
Turns out it's stored as json in the site table, with each Omeka S site having it's own json, naturally. At least there's some logic to it.

**Comment by Bosterm** [comment]
Okay it's pretty unclear exactly how Omeka's ToC and navigation is actually generated, it's built into a bunch of helper entities that are all very new to me. For now, I removed all the code about moving the ToC to the sidebar and instead put the navigation there. I may need you to look into how the navigation is actually structured, or I can look at it later. In the meantime, I'm going to work on some of the other issues.

**Comment by alexdryden** [comment]
It looks like they are using the `Zend\Navigation` module, which uses containers to organize and iterate over pages. To populate the toc they are calling the `getPages()` method on an instance of `Zend\Navigation\Page\Mvc` representing the current "active" page [here](https://github.com/omeka/omeka-s/blob/6a3ec0d28ea73f5b2d653314af535d77735404a6/application/src/Site/BlockLayout/TableOfContents.php#L49-L53). Then the result is passed as a parameter to a partial view to render. 

The `getPages()` method returns the pages inside the container according to the Zend [docs](https://framework.zend.com/apidoc/2.0/classes/Zend.Navigation.Page.Mvc.html#getPages). So, I kinda get why they chose to do it this way, but it mean it won't work as a site/exhibit wide block option. 

If we were to make our own, we could use the same pattern and just call a different method. For now this will work though. I think we can probably get away with just adding some lines in the theme config that lets users turn this on or off and that will provide enough configurability.

**Pull request merged**
