### PR TITLE
Implemented Ellipsis on Truncated Titles

### LINKED ISSUE #2: Elipsis function
Need a function to truncate long titles that can be used for navigation in various parts of the UI

### PR DESCRIPTION
**Pull request by Bosterm**
This will close #2, however, there is a bit of an issue that needs to be fixed before merging. Currently, this is the SCSS for adding ellipses to pagination card titles that are truncated:

`.xxMainLibxx-nav-title {
    max-height: $base-line-height*1.9;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
}`

However, upon compiling, the `-webkit-box-orient: vertical;` rule disappears, so the ellipses do not actually appear. For some reason compiling removes it, and I don't know why. I can't find anything on the internet about Sass compiling removing CSS rules.

Also I'd like to truncate table of contents card titles, which for that I think we could just use the bootstrap class (.text-truncate) since I'd like to leave all of those on one line. However I think that needs to happen on the Mason module now.

### CODE REVIEW

**Comment by alexdryden** [comment]
For adding the `.text-truncate` class to card titles, we actually overwrite the Mason partial with a Theme partial, the same way we overwrite partials from core Omeka. So in the view/common/block-layout you should see the partials for list of exhibits and exhibit contents. 

My best guess on the compiling issue is that somewhere downstream there is something that conflicts with that rule after it is declared? I'll take a look and see if I can figure something out.

**Comment by Bosterm** [comment]
Okay well I've managed to get the ellipses working just fine on the toc cards. I'll keep looking to see if I can find anything about why gulp is removing that rule.

**Comment by Bosterm** [comment]
Okay I found a solution on stackoverflow finally (https://stackoverflow.com/questions/46152850/webkit-box-orient-styling-disappears-from-styling), so feel free to do the review/merge when you're ready.

**Review by alexdryden — APPROVED** [review]
Looks great!

**Pull request merged**
