### PR TITLE
Fix broken merge issue

### PR DESCRIPTION
**Pull request by Bosterm**

### CODE REVIEW

**Comment by Bosterm** [comment]
Somehow the merge you did with the branches didn't keep all of the code that I did, or at least it was a weird version of it. In any case, this one should be correct. The CSS is conflicting, but I think you can just keep the one from this branch.

**Comment by alexdryden** [comment]
@Bosterm I think it might be because this is the getting merged into the develop branch

**Comment by Bosterm** [comment]
Oh shoot you're right, it should be going to UIUC. Let me see if there's a way to fix that or if I just need to do a whole new pull.

**Comment by alexdryden** [comment]
I think we can also revert the i19 pull and then do the merge correctly

**Pull request closed without merging**
