### PR TITLE
Allow Exhibit index to not index self . . .

### LINKED ISSUE #72: Exhibit Index in Nav
Need to find out how to create the index/list of exhibits page and put it on the top nav without the list of exhibits recognizing the index page as an exhibit.

Right now the list of exhibits block assumes that 'chapter' level pages (i.e. 0-level pages in the nav hierarchy) are exhibit index pages. But, to get that index page to show up in the top nav, it needs to added to that hierarchy.

So, we need to get the list of exhibits page to exclude the page it is on. This will solve the problem for most cases.

### PR DESCRIPTION
**Pull request by alexdryden**
. . . when it is in the Navigation at the chapter level. This works with a new form element that Mason is passing to the renderer that lets users select if the current page should be included in the list of exhibits. Closes #72

### CODE REVIEW

**Comment by Bosterm** [comment]
Unfortunately this isn't working for me, and trying to do a console log on `$exhibits[$this->current_page]` returns null, so I suspect that might have something to do with it?

**Comment by alexdryden** [comment]
Oh--forgot to mention: This works in conjunction with a checkbox I added to the List of Exhibits page block in Mason ("check this box to include this page in the list of exhibits"). I thought I did it so it would work even without updating Mason and the block, but I realize now that Mason has to pass the id of the page to exclude to the renderer. 

Any rate, it should work if you update Mason and then update/save the page with the List of Exhibits block.

**Comment by Bosterm** [comment]
No luck, I had also updated Mason and tried removing and re-adding the block. One idea, whenever I re-add the block, it gives me the php error: `Notice: Undefined index: include_self in C:\MAMP\htdocs\omeka-s\modules\Mason\src\Site\BlockLayout\ListOfExhibits.php on line 288`

**Comment by alexdryden** [comment]
Interesting. So the page id that Mason is passing as the current page somehow isn't in the array of pages that the view uses to build the list of exhibits. I thought that wouldn't be possible. Let me double check.

**Comment by alexdryden** [comment]
Doh!! Forgot to push the last commit in mason where I changed the variable name. Okay, the name of the variable that Mason passes should now be the same name that the view is looking for.

**Comment by Bosterm** [comment]
Okay now it works, though oddly enough I still get the php error notice when adding the block, but it still works. My guess is that's more of a Mason issue though.

**Pull request merged**
