### PR TITLE
Retry of merging breadcrumbs style branch

### PR DESCRIPTION
**Pull request by Bosterm**

### CODE REVIEW

**Comment by Bosterm** [comment]
Actually it would be good if you could look at this real quick, since the changed files have nothing to do with this branch, and appear to be more related to the Mason module. I'm more confused now.

**Comment by Bosterm** [comment]
I have a theory, the merge you performed on the previous pull request with this branch appears to have merged UIUC into i_59, not i_59 into UIUC. So it's possible that this undoing of the merge that I just did is just undoing the changes between the two branches. Meanwhile, nothing has actually merged the changes from i_59 into UIUC. Does that make sense?

**Comment by alexdryden** [comment]
Hmm. Yeah the merge of UIUC into i_59 is what GitHub does automatically when you say you've fixed the conflicts. But yeah, what you said made sense. I'll take a look this evening and see if I can get it figured out.

**Comment by alexdryden** [comment]
And I think theoretically merges between two branches with a shared history should always be symmetrical, no matter which order you call them in. Hmm. . . okay, I'm going to try the Occam's razor approach here . . .

**Comment by Bosterm** [comment]
Okay that seems to have worked!

**Comment by alexdryden** [comment]
Yeah, I just did `gulp css`. Don't know why I didn't try that this afternoon at the meeting. I must have kept the wrong side of the merge conflict when I resolved them. So the scss was all correct but the wrong copy of the compiled css was preserved. Doh!

**Pull request merged**
