### PR TITLE
Make nav links fill their parent element

### LINKED ISSUE #86: Navbar: make whole li clickable
Need to make the whole element clickable, not just the text

### PR DESCRIPTION
**Pull request by alexdryden**
This closes #86 by making the link fill its `li` using the `display: inline-block` property and eliminating the padding between the link and its parent `li`. The stretched-link class wouldn't work because it messes up the other ::after pseudo elements used to show the child pages and a few other issues.

### CODE REVIEW

**Comment by Bosterm** [comment]
This worked, but it's causing there to be about 4 pixels of the blue navbar to appear above the white background of an active page if that page is a root exhibit page. Any pages that aren't exhibits/have children, such as the home page/list of exhibits page, do not have these 4 pixels above, so the tabs are different heights as result.
Capture

**Comment by alexdryden** [comment]
Oh interesting. It isn't doing that for me, and I'm guessing it is because I have only exhibit pages and no 0-children index pages.

**Comment by alexdryden** [comment]
Okay, this should be fixed now.

**Comment by Bosterm** [comment]
I made a quick adjustment to the style, but now it's conflicting. Could you do the merge fix thing @alexdryden?

**Comment by alexdryden** [comment]
@Bosterm That should do it!

**Pull request merged**
