### PR TITLE
Searchbar Style

### LINKED ISSUE #75: Style Search Box

### PR DESCRIPTION
**Pull request by Bosterm**
Added some additional style/functionality to searchbar. Mostly when you click on it, it expands in width, the searchbar has a box shadow, and the search button changes to blue.

Closes #75

### CODE REVIEW

**Comment by Bosterm** [comment]
Don't merge this yet, I realized I had to make an adjustment for Chrome.

**Comment by Bosterm** [comment]
Okay now it can be merged.

**Comment by alexdryden** [comment]
I'm getting a slight gap between the expanded search bar and the border on the left side in Firefox and Safari on default magnification and full screen:
Screen Shot 2020-12-09 at 6 15 41 PM
Both shrinking the screen and increasing the magnification make the problem go away

**Comment by Bosterm** [comment]
Shoot, that's because you have a higher resolution monitor than me, and I didn't think to test for those screen resolutions with this. I think it should be an easy fix though (hopefully)

**Comment by Bosterm** [comment]
Okay I ended making more tweaks than even the one you noticed, but I'm pretty sure it should be working properly now.

**Pull request merged**
