### PR TITLE
Add alt text to bottom nav images

### LINKED ISSUE #6: Alt Text for Nav Image
Need some way to either gather, generate or allow users to input an alt text for the navigation images in issue #4

### PR DESCRIPTION
**Pull request by alexdryden**
This closes #6 by getting alt text from the AltText module or assigning default text if the module is not installed or the field is left blank.

### CODE REVIEW

**Comment by alexdryden** [comment]
I'm pretty sure that the conflict is just because I started this branch before you fixed the bug in #22 so this branch has a different history than UIUC.

**Comment by Bosterm** [comment]
This all seems to be working okay (I'm going to double check the conflict soon, but I think you're right about what's causing it). I have a quick question: where exactly does the alt text come from? I've tried adding various metadata, but it's still giving me the fallback alt text.

**Comment by alexdryden** [comment]
Oh right, it comes from the AltText Module: https://github.com/zerocrates/AltText. So you'll have to install the module. It only allows you to add alt text to media on the edit view. I really can't fathom why alt text wasn't included as a core feature or why you can only add it in the edit view through the module.

But, a more detailed explanation of where it comes from . . . all of the resources extent the class `AbstractResourceEntityRepresentation`, which has an event trigger in the `jsonSerialize()` method that modules can listen for (similar to the hooks in Omeka classic) and inject their own values into. So the other json-ld methods that get the linked data (`getJsonLd()` and `getResourceJsonLd()`) will not have any of the data added from modules.

**Comment by Bosterm** [comment]
Unfortunately I'm having trouble getting the alt text I'm adding with the module to appear on the nav buttons, but that could have more to do with my install rather than this code. (though the alt text is showing up on the media embed, go figure). Any ideas? If you think it will work on the library site, then that should be enough, and I can go ahead and merge.

**Comment by alexdryden** [comment]
Doh! Try it now. I changed the index name when testing to see what kind of error it would throw if the module wasn't installed and forgot to change it back.

**Pull request merged**
