### PR TITLE
Nav dropdown style

### LINKED ISSUE #90: Nav bar on hover issue
This is breaking down the lingering navbar issues into components. 
> I'm not a huge fan of the appearance/structure of the content that appears on hover. I didn't want to adjust anything until we had a firm idea of what pages would be going on this navbar.

### PR DESCRIPTION
**Pull request by Bosterm**
This closes #90.

### CODE REVIEW

**Comment by Bosterm** [comment]
Don't merge this yet, I noticed a minor issue with hovering.

**Comment by Bosterm** [comment]
Okay now this can be merged.

**Comment by alexdryden** [comment]
looks good!

**Review by alexdryden — COMMENTED** [review]
works as expected, looks nice

**Pull request merged**
